### ISSUE TITLE
Release EXE requires JRE to run

### ISSUE THREAD

**Issue by RichyHBM** [markusaksli/TradeBot#11]
**Describe the bug**
As per the title, the current EXE doesn't run when the JRE is not present, further more I have installed Java 11 JDK and it doesnt recognise that either (though that may be my system/java setup)

**To Reproduce**
Download EXE
Run Tradebot.exe
Program prints "TradeBot: This application requires a Java Runtime Environment 1.8 - 12"

**Logs**
TradeBot: This application requires a Java Runtime Environment 1.8 - 12

**Desktop:**
 - OS: Windows 10

**Comment by markusaksli** [comment]
I was a bit confused as to how `launch4j` includes the bundled JRE but the latest version https://github.com/markusaksli/TradeBot/releases/tag/v0.8.2 should fix this.

It now includes a proper stripped JRE made from JDK 11 with `jlink` and the proper path to it in the exe.

Let me know if it doesn't work for you.
