### ISSUE TITLE
linux

### ISSUE THREAD

**Issue by bummar** [markusaksli/TradeBot#17]
Can it run on linux?

**Comment by markusaksli** [comment]
We can add a jar to the releases so you can run that with JDK 11 but the current executable solution is only for windows.

**Comment by bummar** [comment]
That would be great, to be able to test it on linux, what I think can be complicated is the persistence of the console. And that would take a frontend development ... thank you!

**Comment by Albert-davil** [comment]
How to report facebook id, using kali linux, (please tell me)

**Comment by markusaksli** [comment]
Jar has been added to the latest release, closing this since a more permanent solution seems a bit too complicated and there will be other priorities for a while.
