### ISSUE TITLE
Backtesting problem

### ISSUE THREAD

**Issue by k4m4h4l** [markusaksli/TradeBot#33]
As I understand it, before we can backtest, it would be necessary to use the collect function first.

but then this problem happens:

collection

---Entering collection mode
---No backtesting files detected
Enter collectable currency (BTC, LINK, ETH...)
BTC
Invalid symbol.
BTCUSD
Invalid symbol.

IT DOESN'T MATTER WHICH SYMBOL I PUT THE RESULT THAT I SEE INVALID SYMBOL

**Comment by markusaksli** [comment]
Make sure your FIAT currency is set up in the config, since it adds it to the symbol, wasn't able to reproduce this issue
