### ISSUE TITLE
RSI badly computed

### ISSUE THREAD

**Issue by domiguil** [markusaksli/TradeBot#35]
RSI check is baddly computed as it cannot return -2 because **temp > NEGATIVE_MIN** (70 by default) is computed before **temp > NEGATIVE_MAX** (80 by default)

RSI.java line 93

Reverse the 2 tests

**Comment by markusaksli** [comment]
Fixed in https://github.com/markusaksli/TradeBot/commit/f5ae0aaa0a95de27594399d39fe17141c51aa7c8
