### ISSUE TITLE
maybe a stupid question

### ISSUE THREAD

**Issue by GabriGitDev** [markusaksli/TradeBot#39]
Describe what you would like to be changed, added, or improved.
the bot must run 24/7 or it works also if the pc is turned off or the application is closed?

**Comment by markusaksli** [comment]
Well the bot doesn't run on magic so yes the application needs to be open for it to run. If you close the application or your computer then it will stop. Currently, it might also get automatically disconnected from the API after 24h. Once the rework is out this should get addressed. To run this 24/7 you would either have to run it on your PC 24/7 or use AWS or Azure to run it in your own VM or server
